import Card from "@/components/Card";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";

const certificates = () => {
  return (
    <>
      <Head>
        <title>Octivion | Certificates</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          {/* <Card /> */}
          <p className="text-center">Oops! Page under construction.</p>
        </Layout>
      </main>
    </>
  );
};

export default certificates;
